baseURL = "https://npodlozhniy.github.io/"
languageCode = "en-gb"
title = "Nikita Podlozhnyi"
theme = "PaperMod"
publishDir = "docs"
paginate = 3

[params]
defaultTheme = "dark"
disableThemeToggle = false

ShowShareButtons = true
ShareButtons = ["telegram", "linkedin", "facebook"]
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowWordCount = false

# ShowRssButtonInSectionTermList = true

showtoc = true
tocopen = true

  # if failed to find a valid digest in the 'integrity' attribute for resource bug
  # [params.assets]
  # disableFingerprinting = true

  [params.profileMode]
  enabled = true
  title = "Nikita Podlozhnyi"
  subtitle = "Senior Data Scientist"
  imageUrl = "https://avatars.githubusercontent.com/NPodlozhniy"
  imageTitle = "Image by Author"

    [[params.profileMode.buttons]]
    name = "Download Resume"
    url = "PodlozhnyiNikitaCV.pdf"

	[[params.socialIcons]]
	name = "linkedin"
	title = "LinkedIn"
	url = "https://www.linkedin.com/in/niki4-inc/"

	[[params.socialIcons]]
	name = "github"
	title = "GitHub"
	url = "https://github.com/NPodlozhniy"
 
  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]


[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
identifier = "search"
name = "Search"
url = "search"
weight = 3

[[menu.main]]
identifier = "archives"
name = "Archive"
url = "archives"
weight = 4



