baseURL = "https://npodlozhniy.github.io/"
languageCode = "en-gb"
title = "Nikita Podlozhniy"
theme = "PaperMod"
publishDir = "docs"
paginate = 3

googleAnalytics = "G-ESWD18X008"

[params]

env = "production"

defaultTheme = "dark"
disableThemeToggle = false

ShowShareButtons = true
ShareButtons = ["twitter", "telegram", "linkedin", "facebook"]
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowWordCount = false

ShowRssButtonInSectionTermList = true

showtoc = true
tocopen = true

comments = true

  # if failed to find a valid digest in the 'integrity' attribute for resource bug
  # [params.assets]
  # disableFingerprinting = true

  [params.profileMode]
  enabled = true
  title = "Nikita Podlozhniy"
  subtitle = "Senior Data Scientist"
  imageUrl = "https://avatars.githubusercontent.com/NPodlozhniy"
  imageTitle = "Image by Author"

    [[params.profileMode.buttons]]
    name = "Download Resume"
    url = "PodlozhnyiNikitaCV.pdf"

  [[params.socialIcons]]
  name = "linkedin"
  title = "LinkedIn"
  url = "https://www.linkedin.com/in/niki4-inc/"

  [[params.socialIcons]]
  name = "github"
  title = "GitHub"
  url = "https://github.com/NPodlozhniy"

[languages]

  [languages.en]
  languageName = ":en:"
  languageAltTitle = "English"
  weight = 10
  [languages.en.menu]

    [[languages.en.menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

	[[languages.en.menu.main]]
	identifier = "posts"
	name = "Posts"
	url = "/posts/"
	weight = 2

	[[languages.en.menu.main]]
	identifier = "search"
	name = "Search"
	url = "search"
	weight = 3

	[[languages.en.menu.main]]
	identifier = "archives"
	name = "Archive"
	url = "archives"
	weight = 4

  [languages.ru]
  languageName = ":ru:"
  languageAltTitle = "Russian"
  weight = 1
  title = "Подложный Никита"
  [languages.ru.menu]

	[[languages.ru.menu.main]]
	identifier = "home"
	name = "Главная"
	url = "/"
	weight = 1

	[[languages.ru.menu.main]]
	identifier = "posts"
	name = "Статьи"
	url = "/posts/"
	weight = 2

	[[languages.ru.menu.main]]
	identifier = "search"
	name = "Поиск"
	url = "search"
	weight = 3

	[[languages.ru.menu.main]]
	identifier = "archives"
	name = "Архив"
	url = "archives"
	weight = 4


  [languages.ru.profileMode]
  enabled = true
  title = "Подложный Никита"
  imageUrl = "https://avatars.githubusercontent.com/NPodlozhniy"
  subtitle = "Опытный аналитик данных"

    [[languages.ru.profileMode.buttons]]
    name = "Скачать Резюме"
    url = "PodlozhnyiNikitaCV.pdf"


[outputs]
home = ["HTML", "RSS", "JSON"]
